from . import jt_client
from . import jt_police
from . import jt_transaction
from . import jt_activite
from . import jt_email_ai
from . import jt_tache
from . import doorway_crm_mailbox
from . import jt_dashboard
from . import res_users
from . import calendar_event
from . import jt_sync_cookie
from . import jt_sync_import
