{
    'name': 'Rénovation Conciergerie',
    'version': '19.0.1.27.8',
    'category': 'Services',
    'summary': 'Gestion partenaires, services, zones et forfaits leads',
    'depends': ['base', 'mail', 'sms', 'contacts', 'crm', 'calendar', 'project', 'account', 'sale', 'gamification', 'gamification_sale_crm', 'base_automation', 'doorway_onboarding', 'doorway_agents_dashboard', 'intellix_branding'],
    'data': [
        'security/agence_crm_security.xml',
        'security/doorway_segment_security.xml',
        'security/crm_access_levels.xml',
        'security/pipeline_assigned_security.xml',
        'security/automation_security.xml',
        'security/partner_security.xml',
        'security/doorway_equipe_interne.xml',
        'security/ir.model.access.csv',
        'security/rdv/ir.model.access.csv',
        'security/rdv_security.xml',
        'data/doorway_session_stability.xml',
        'data/res_partner_category_reno_immo.xml',
        'data/renovation_secteur_tarif_data.xml',
        'data/renovation_forfait_type_data.xml',
        'data/onboarding.xml',
        'data/assets.xml',
        'data/service_categories.xml',
        'data/mail_templates.xml',
        'data/message_templates.xml',
        'data/crm_pipelines.xml',
        'data/crm_immo_meta.xml',
        'data/crm_energie_tags.xml',
        'data/crm_haidly_tags.xml',
        'data/energie_webhook_data.xml',
        'data/haidly_webhook_data.xml',
        'data/haidly_elevenlabs_webhook.xml',
        'data/meta_immo_elevenlabs_webhook.xml',
        'data/energie_elevenlabs_webhook.xml',
        'data/energie_meta_pages.xml',
        'data/meta_leads_global_map.xml',
        'data/maison_immo_reference.xml',
        'data/maison_immo_cleanup.xml',
        'data/crm_test_leads_cleanup.xml',
        'data/crm_agent_ia_rename.xml',
        'data/automation_config.xml',
        'data/automation_rules.xml',
        'data/gamification_data.xml',
        'data/project_crons.xml',
        'data/ai_prompts.xml',
        'data/menu_order.xml',
        'data/account_payment_methods.xml',
        'views/renovation_service_category_views.xml',
        'views/renovation_forfait_type_views.xml',
        'views/renovation_partner_package_views.xml',
        'views/res_partner_views.xml',
        'views/res_users_views.xml',
        'views/pipeline_assigned_menus.xml',
        'views/menu_consolidation.xml',
        'views/crm_lead_views.xml',
        'views/crm_lead_agent_ia_views.xml',
        'views/crm_lead_immo_meta_views.xml',
        'views/crm_lead_dave_booking_views.xml',
        'views/book_martin_wizard_views.xml',
        'views/crm_lead_martin_booking_views.xml',
        'views/renovation_partner_rdv_views.xml',
        'views/crm_lead_energie_views.xml',
        'views/crm_lead_haidly_views.xml',
        'views/crm_lead_synthesis_views.xml',
        'views/crm_pipeline_switcher_views.xml',
        'views/crm_pipeline_menus.xml',
        'views/crm_prorated_revenue_views.xml',
        'views/automation_menus.xml',
        'views/messaging_views.xml',
        'views/meta_leads_map_wizard_views.xml',
        'views/renovation_config_settings_views.xml',
        'views/twilio_views.xml',
        'views/ai_log_views.xml',
        'views/ai_prompt_views.xml',
        'views/project_ai_task_views.xml',
        'views/project_ai_user_reco_views.xml',
        'views/project_gamification_views.xml',
        'views/partner_portal_views.xml',
        'views/renovation_credit_views.xml',
        'views/sale_order_views.xml',
        'views/account_payment_register_views.xml',
        'views/ux_ui_views.xml',
        'views/login_fix_views.xml',
        'views/intellix_legal_pages.xml',
        'views/reno_immobilier_app.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'renovation_conciergerie/static/src/css/forfait_form.css',
            'renovation_conciergerie/static/src/css/reno_martin_slots.css',
            'renovation_conciergerie/static/src/css/reno_partner_crm.css',
            'renovation_conciergerie/static/src/js/reno_martin_slots.js',
            'renovation_conciergerie/static/src/xml/reno_martin_slots.xml',
        ],
        'web.assets_web_dark': [
            'renovation_conciergerie/static/src/css/forfait_form.css',
            'renovation_conciergerie/static/src/css/reno_martin_slots.css',
            'renovation_conciergerie/static/src/css/reno_partner_crm.css',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': True,
}
