# -*- coding: utf-8 -*-
{
    "name": "Doorway CRM",
    "version": "19.0.1.8.10",
    "category": "Sales/CRM",
    "summary": "Fiche opportunité B2C, navigation, activités inline, calendrier",
    "depends": ["crm", "calendar", "mail", "intellix_branding", "renovation_conciergerie"],
    "external_dependencies": {
        "python": ["requests"],
    },
    "data": [
        "security/ir.model.access.csv",
        "security/mail_activity_security.xml",
        "data/crm_stages.xml",
        "data/crm_lost_reason.xml",
        "views/business_card_scan_action.xml",
        "views/partner_form_business_card.xml",
        "views/doorway_crm_lead_form.xml",
        "views/doorway_crm_lead_form_renovation.xml",
        "views/mail_activity_schedule_views.xml",
        "views/crm_lead_lost_views.xml",
        "views/doorway_crm_activity_calendar.xml",
        "views/doorway_crm_mailbox_setup_views.xml",
        "views/doorway_crm_mailbox_views.xml",
        "views/doorway_crm_webmail_views.xml",
        "views/doorway_crm_mailbox.xml",
        "views/doorway_crm_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "doorway_crm/static/src/css/doorway_crm.css",
            "doorway_crm/static/src/css/intellix_voice_fill.css",
            "doorway_crm/static/src/css/doorway_webmail.css",
            "doorway_crm/static/src/css/business_card_scan.css",
            "doorway_crm/static/src/js/doorway_webmail.js",
            "doorway_crm/static/src/js/intellix_voice_fill.js",
            "doorway_crm/static/src/js/business_card_scan.js",
            "doorway_crm/static/src/js/business_card_scan_systray.js",
            "doorway_crm/static/src/xml/doorway_webmail.xml",
            "doorway_crm/static/src/xml/business_card_scan.xml",
            "doorway_crm/static/src/xml/business_card_scan_systray.xml",
        ],
    },
    "installable": True,
    "application": False,
    "license": "LGPL-3",
    "post_init_hook": "post_init_hook",
}
