# -*- coding: utf-8 -*-
from . import coins_assignee_mixin
from . import coins_influenceur
from . import coins_entente
from . import coins_entente_devis_offer
from . import coins_entente_standard
from . import coins_entente_activation
from . import coins_partenaires_dashboard
from . import coins_overview
from . import crm_lead_partenariat
from . import crm_lead_envoyer_signature
from . import coins_partenariat_kpi
from . import crm_lead_voyageur
from . import coins_lead_classification
from . import product_template
from . import sale_order
from . import sale_order_djemanna_freeze
from . import account_move
from . import payment_provider
from . import res_partner
from . import res_users
from . import ir_ui_menu
from . import crm_lead_cm_purge
from . import crm_lead_send_fiche
