# -*- coding: utf-8 -*-

from . import establishment
from . import ir_ui_menu
from . import payment_provider
from . import property_room
from . import reservation
from . import channex_demo
from . import res_users
from . import space_mode
from . import table
from . import wellness_type
from . import practitioner
from . import wellness_slot
from . import event_template
from . import event
from . import event_task
from . import pe_employee_profile
from . import hr_employee
from . import menu_item
from . import staff_role
from . import pe_presence
from . import presence_correction
from . import pe_absence
from . import dashboard
from . import privatisation
from . import police_fiche
from . import tax_bordereau
from . import experience_agent
from . import ota_review_score
from . import portal_dashboard
from . import pricing
from . import cross_promo
