# -*- coding: utf-8 -*-
from . import coins_property_category
from . import coins_property
from . import coins_property_photo_category
from . import coins_property_photo
from . import coins_property_room
from . import coins_property_ops_slot
from . import coins_property_disponibilite
from . import coins_property_blocage
from . import coins_property_airbnb_sync
from . import coins_partner_activity
from . import coins_fiche_video
from . import coins_fiche_video_view
from . import coins_driver
from . import coins_driver_contrat
from . import coins_driver_mouvement
from . import coins_driver_remise
from . import coins_reservation
from . import coins_reservation_line
from . import coins_partner_interest
from . import res_partner
from . import coins_wa_session
from . import coins_detente_massage_type
from . import coins_detente_partner
from . import coins_detente_service
from . import coins_detente_package
from . import coins_detente_booking
from . import coins_activite
from . import coins_activite_booking
from . import coins_yasmine_conversation
from . import coins_carnet_tier
from . import coins_carnet
from . import coins_carnet_favori
from . import coins_ambassador
from . import coins_overview
from . import coins_calendar_helpers
from . import calendar_event_coins
from . import coins_evenement
from . import coins_evenement_invite
from . import coins_evenement_prestataire
from . import coins_property_evenement
from . import coins_prestataire
from . import coins_deco_prestataire
from . import coins_deco_prestataire_photo
from . import crm_lead_evenement
from . import crm_lead_deco
from . import crm_lead_events_sheet_sync
from . import coins_channex_mapping
from . import coins_channex_push
from . import coins_channex_revision
from . import coins_channex_config
from . import coins_channex_calendar
from . import coins_concierge_line
from . import coins_property_channex
from . import coins_property_review
