# -*- coding: utf-8 -*-
from odoo import api, fields, models

class CoinsDetentePartner(models.Model):
    _name = 'coins.detente_partner'
    _description = 'coins.detente_partner'
    _inherit = ['mail.thread', 'mail.activity.mixin']

    partner_id = fields.Many2one('res.partner')
    currency_id = fields.Many2one('res.currency')
    quality_score = fields.Integer()
    name = fields.Char()
    partner_type = fields.Char()
    neighborhood = fields.Char()
    phone = fields.Char()
    whatsapp = fields.Char()
    contact_person = fields.Char()
    commission_type = fields.Char()
    massage_types = fields.Char()
    verdict = fields.Char()
    notes = fields.Text()
    public_price_pool = fields.Float()
    public_price_hammam_massage = fields.Float()
    public_price_dinner_show = fields.Float()
    partner_price_pool = fields.Float()
    partner_price_hammam_massage = fields.Float()
    partner_price_dinner_show = fields.Float()
    active = fields.Boolean()
    has_pool = fields.Boolean()
    has_hammam = fields.Boolean()
    has_massage = fields.Boolean()
    has_restaurant = fields.Boolean()
    commission_value = fields.Float()
    camping_capacity = fields.Integer()
    noise_curfew_time = fields.Char()
    public_price_bbq_chef = fields.Float()
    public_price_cours_cuisine = fields.Float()
    public_price_sortie_soiree = fields.Float()
    public_price_fermette_journee = fields.Float()
    public_price_camping_nuitee = fields.Float()
    public_price_dj_soiree = fields.Float()
    partner_price_bbq_chef = fields.Float()
    partner_price_cours_cuisine = fields.Float()
    partner_price_sortie_soiree = fields.Float()
    partner_price_fermette_journee = fields.Float()
    partner_price_camping_nuitee = fields.Float()
    partner_price_dj_soiree = fields.Float()
    has_bbq_chef = fields.Boolean()
    has_cours_cuisine = fields.Boolean()
    has_sortie_soiree = fields.Boolean()
    has_fermette_camping = fields.Boolean()
    has_dj_soiree = fields.Boolean()
    alcohol_authorized = fields.Boolean()
    has_security_night = fields.Boolean()
    is_chef_multi_service = fields.Boolean()
    is_owned_equipment = fields.Boolean()
    property_id = fields.Many2one('coins.property')
    direct_rental_price_base = fields.Float()
    direct_rental_markup_fixed = fields.Float()
    direct_rental_client_price = fields.Monetary(currency_field='currency_id')
    direct_rental_owner_payout = fields.Float()
    direct_rental_margin = fields.Monetary(currency_field='currency_id')
    available_for_direct_rental = fields.Boolean()
    direct_rental_commission_percent = fields.Float()
    booking_count = fields.Integer()
    service_count = fields.Integer()

    massage_type_ids = fields.Many2many('coins.detente_massage_type', 'coins_detente_partner_massage_rel', 'partner_id', 'massage_type_id', string = 'Types de massage')
    service_ids = fields.One2many('coins.detente_service', 'partner_id', string = 'Catalogue prestations')
    package_ids = fields.Many2many('coins.detente_package', 'coins_detente_package_partner_rel', 'partner_id', 'package_id', string = 'Forfaits')
