# -*- coding: utf-8 -*-
from . import mixin_cad
from . import coins_assignee_mixin
from . import property
from . import reservation
from . import partner_activity
from . import evenement
from . import prestataire
from . import driver
from . import forfait
from . import carnet
from . import ota
from . import partenariat
from . import partenariat_contact
from . import calendar_event
from . import voyageur
from . import dashboard
from . import partenariat_lines
from . import boost_request
from . import partenariat_portal
from . import mon_coin_demo
from . import crm_lead_mon_coin
from . import product_template
from . import sale_order
from . import partenariat_catalog
from . import partenariat_bonus
from . import partenariat_entente
from . import rdv
