# -*- coding: utf-8 -*-
{
    "name": "Module Hébergement",
    "version": "19.0.1.16.0",
    "category": "Services",
    "summary": "Back-office multi-établissements : chambres, réservations, terrasse, bien-être",
    "description": """
Module Hébergement — produit IntelliX réutilisable.

S'appuie sur coins.reservation / coins.property (source de vérité Channex),
doorway_messaging et doorway_social_ia. N'altère pas la logique de sync Channex.
    """,
    "author": "IntelliX / Agence Doorway",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "web",
        "coins_marocain",
        "doorway_messaging",
        "doorway_social_ia",
        "people_engine",
        "payment",
    ],
    "data": [
        "security/riad_security.xml",
        "security/ir.model.access.csv",
        "data/wellness_service_types.xml",
        "data/establishment_anna_sweety.xml",
        "data/company_anna_sweety.xml",
        "data/menu_anna_sweety.xml",
        "data/payroll_cron.xml",
        "data/event_templates.xml",
        "data/staff_roles.xml",
        "data/event_task_cron.xml",
        "data/police_sequence.xml",
        "data/tax_bordereau_marrakech.xml",
        "data/tourist_tax_cron.xml",
        "data/police_checkin_cron.xml",
        "data/experience_cron.xml",
        "data/pricing_cron.xml",
        "data/cross_promo_anna.xml",
        "data/channex_demo.xml",
        "report/police_fiche_templates.xml",
        "report/tax_bordereau_templates.xml",
        "views/establishment_views.xml",
        "views/payment_views.xml",
        "views/payment_provider_views.xml",
        "views/checkin_templates.xml",
        "views/reservation_views.xml",
        "views/cross_promo_views.xml",
        "views/police_views.xml",
        "views/tax_bordereau_views.xml",
        "views/experience_views.xml",
        "views/ota_review_views.xml",
        "views/pricing_views.xml",
        "views/space_mode_views.xml",
        "views/table_views.xml",
        "views/practitioner_views.xml",
        "views/wellness_views.xml",
        "views/event_views.xml",
        "views/staff_views.xml",
        "views/menu_views.xml",
        "views/menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "intellix_riad/static/src/css/riad.css",
            "intellix_riad/static/src/js/labels.js",
            "intellix_riad/static/src/js/shell.js",
            "intellix_riad/static/src/js/webclient.js",
            "intellix_riad/static/src/js/dashboard.js",
            "intellix_riad/static/src/js/fleet.js",
            "intellix_riad/static/src/js/calendar.js",
            "intellix_riad/static/src/js/pages.js",
            "intellix_riad/static/src/xml/shell.xml",
            "intellix_riad/static/src/xml/webclient.xml",
            "intellix_riad/static/src/xml/dashboard.xml",
            "intellix_riad/static/src/xml/fleet.xml",
            "intellix_riad/static/src/xml/calendar.xml",
            "intellix_riad/static/src/xml/pages.xml",
        ],
        "web.assets_web_dark": [
            "intellix_riad/static/src/css/riad.css",
        ],
    },
    "application": True,
    "installable": True,
}
