from . import renovation_service_category
from . import renovation_package_type
from . import renovation_secteur_tarif
from . import renovation_forfait_type
from . import renovation_forfait_credit
from . import renovation_partner_package
from . import renovation_partner_postal_code
from . import crm_lead_pipeline
from . import crm_lead_reno_immobilier
from . import crm_lead_assurance
from . import crm_lead_gamification
from . import gamification_challenge_announce
from . import crm_team_pipeline
from . import ir_actions_act_window
from . import website_lead_webhook
from . import assurance_webhook
from . import renovation_lead_assignment
from . import renovation_lead_assignment_availability
from . import renovation_lead_service_assignment
from . import twilio_call_log
from . import retell_call_log
from . import retell_webhook
from . import crm_lead_immo_meta
from . import crm_lead_energie
from . import crm_lead_haidly
from . import crm_lead_source_ia
from . import elevenlabs_postcall
from . import meta_leads_routing
from . import meta_leads_map_wizard
from . import meta_immo_webhook
from . import energie_webhook
from . import haidly_webhook
from . import meta_marketing_webhook
from . import meta_leadgen_webhook
from . import ai_service
from . import ai_log
from . import ai_prompt
from . import project_ai_task
from . import project_ai_assistant
from . import project_task_followup
from . import project_task_gamification
from . import project_ai_analysis
from . import project_ai_email
from . import project_ai_user_reco
from . import project_ai_help
from . import project_ai_chat
from . import res_config_settings
from . import res_partner
from . import res_partner_crm
from . import renovation_partner_interaction
from . import res_partner_coverage_labels
from . import res_users
from . import discuss_partner_restrict
from . import ir_http
from . import ir_ui_menu
from . import ir_cron
from . import sale_order
from . import mail_mail
from . import ir_mail_server
from . import account_payment_method
from . import account_payment_register
from . import account_account
from . import crm_lead_dave_booking
from . import reno_rdv_tz
from . import renovation_partner_rdv
from . import crm_lead_martin_booking
from . import calendar_event_reno_rdv
