# -*- coding: utf-8 -*-
{
    "name": "Doorway — Demo Call Center",
    "version": "19.0.1.2.8",
    "category": "Sales",
    "summary": "Espace demo isolé — campagnes, agents, crédits et devis par client",
    "depends": [
        "base",
        "mail",
        "crm",
        "sale",
        "sale_management",
        "product",
        "calendar",
        "doorway_credits",
        "doorway_agents_dashboard",
        "doorway_vicidial_campaigns",
        "doorway_onboarding",
        "people_engine",
        "renovation_conciergerie",
    ],
    "data": [
        "security/demo_security.xml",
        "security/ir.model.access.csv",
        "views/res_users_views.xml",
        "views/tenant_views.xml",
        "views/campaign_demo_views.xml",
        "views/agent_demo_views.xml",
        "views/call_demo_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
