# -*- coding: utf-8 -*-
{
    "name": "Intellix — Support",
    "version": "19.0.2.16.0",
    "category": "Services/Helpdesk",
    "summary": "Tickets support, diagnostic auto, Copilot et AnyDesk",
    "description": """
        Module support Intellix : Kanban tickets, diagnostic client vs plateforme,
        panneau Copilot (phase 2), workflow AnyDesk, intégration campagnes Doorway.
    """,
    "author": "Agence Doorway",
    "depends": [
        "base",
        "mail",
        "crm",
        "contacts",
        "web",
        "base_setup",
        "intellix_branding",
    ],
    "data": [
        "security/intellix_support_security.xml",
        "security/intellix_support_record_rules.xml",
        "security/ir.model.access.csv",
        "data/sequence_data.xml",
        "data/category_data.xml",
        "data/stage_data.xml",
        "data/stage_closed_data.xml",
        "data/runbook_data.xml",
        "data/runbook_phase_data.xml",
        "data/mail_template_data.xml",
        "data/cron_data.xml",
        "data/support_user_sync.xml",
        "views/support_fonts.xml",
        "views/support_stage_views.xml",
        "views/support_category_views.xml",
        "views/support_ticket_create_wizard_views.xml",
        "views/support_ticket_views.xml",
        "views/support_diagnostic_views.xml",
        "views/support_runbook_views.xml",
        "views/support_fix_proposal_views.xml",
        "views/res_partner_views.xml",
        "views/crm_lead_views.xml",
        "views/res_config_settings_views.xml",
        "views/menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "intellix_support/static/src/css/support.css",
            "intellix_support/static/src/xml/support_kanban.xml",
            "intellix_support/static/src/js/support_kanban_controller.js",
            "intellix_support/static/src/js/support_form_controller.js",
            "intellix_support/static/src/js/support_copilot_panel.js",
            "intellix_support/static/src/xml/support_copilot_panel.xml",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
    "post_init_hook": "post_init_hook",
}
