# -*- coding: utf-8 -*-
{
    "name": "IntelliX — Messaging Unifié",
    "version": "19.0.1.8.4",
    "category": "Marketing/Communication",
    "summary": "Boîte de réception e-mail, envoi multi-canal : Email, SMS, WhatsApp",
    "depends": [
        "base",
        "mail",
        "crm",
        "contacts",
        "web",
        "base_setup",
        "mass_mailing",
        "mass_mailing_sms",
        "intellix_branding",
        "doorway_crm",
    ],
    "external_dependencies": {
        "python": ["requests"],
    },
    "data": [
        "security/messaging_security.xml",
        "security/ir.model.access.csv",
        "data/default_templates_data.xml",
        "data/cron_data.xml",
        "views/channel_config_views.xml",
        "views/template_views.xml",
        "views/campaign_views.xml",
        "views/log_views.xml",
        "views/compose_wizard_views.xml",
        "views/bulk_select_wizard_views.xml",
        "views/res_config_settings_views.xml",
        "views/wa_log_views.xml",
        "views/whatsapp_log_views.xml",
        "views/wa_wizard_views.xml",
        "views/whatsapp_send_wizard_views.xml",
        "views/crm_lead_wa_views.xml",
        "views/messaging_hub_views.xml",
        "views/menu_views.xml",
        "views/inbox_menus.xml",
        "views/assign_campaign_wizard_views.xml",
        "views/marketing_menus_integration.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "doorway_messaging/static/src/css/messaging.css",
            "doorway_messaging/static/src/css/messaging_hub.css",
            "doorway_messaging/static/src/css/messaging_wizard.css",
            "doorway_messaging/static/src/css/whatsapp_wizard.css",
            "doorway_messaging/static/src/xml/messaging_hub.xml",
            "doorway_messaging/static/src/xml/whatsapp_wizard.xml",
            "doorway_messaging/static/src/js/compose_editor.js",
            "doorway_messaging/static/src/js/messaging_hub.js",
            "doorway_messaging/static/src/js/whatsapp_wizard.js",
            "doorway_messaging/static/src/js/webmail_compose_param.js",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
