# -*- coding: utf-8 -*-
{
    "name": "Doorway Appels",
    "version": "19.0.3.66",
    "category": "CRM",
    "depends": [
        "base",
        "mail",
        "web",
        "crm",
        "doorway_crm",
        "calendar",
        "hr",
        "renovation_conciergerie",
        "intellix_branding",
        "doorway_agents_dashboard",
        "doorway_onboarding",
    ],
    "external_dependencies": {
        "python": ["mysql-connector-python", "requests"],
    },
    "data": [
        "security/vicidial_qualification_security.xml",
        "security/ir.model.access.csv",
        "data/vicidial_qualification_pipeline.xml",
        "data/vicidial_qualification_cron.xml",
        "data/vicidial_webrtc_cron.xml",
        "data/cron_data.xml",
        "data/ai_call_throttle_params.xml",
        "data/campaigns_data.xml",
        "data/renofacile_consent_tags.xml",
        "views/vicidial_qualification_views.xml",
        "views/vicidial_qualification_hub_views.xml",
        "views/vicidial_workstation_views.xml",
        "views/calls_coaching_dashboard_views.xml",
        "views/my_coaching_dashboard_views.xml",
        "views/supervisor_dashboard_views.xml",
        "data/onboarding.xml",
        "views/call_log_views.xml",
        "views/campaign_menu.xml",
        "views/campaign_list.xml",
        "views/campaign_performance_views.xml",
        "views/agent_performance_form_tab.xml",
        "views/agent_performance_search.xml",
        "views/campaign_form.xml",
        "views/campaign_dashboard.xml",
        "views/campaign_dashboard_views.xml",
        "data/vicidial_qualification_setup.xml",
        "data/rappel_quebec_setup.xml",
        "data/vicidial_ai_prompts.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "doorway_vicidial_campaigns/static/src/xml/campaign_monitor.xml",
            "doorway_vicidial_campaigns/static/src/xml/campaign_dashboard.xml",
            "doorway_vicidial_campaigns/static/src/js/campaign_monitor.js",
            "doorway_vicidial_campaigns/static/src/js/campaign_dashboard.js",
            "doorway_vicidial_campaigns/static/src/css/campaign_monitor.css",
            "doorway_vicidial_campaigns/static/src/css/campaign_dashboard.css",
            "doorway_vicidial_campaigns/static/src/js/vicidial_lead_sync.js",
            "doorway_vicidial_campaigns/static/src/js/vicidial_workstation.js",
            "doorway_vicidial_campaigns/static/src/xml/vicidial_workstation.xml",
            "doorway_vicidial_campaigns/static/src/css/vicidial_qualification.css",
            "doorway_vicidial_campaigns/static/src/css/vicidial_workstation.css",
            "doorway_vicidial_campaigns/static/src/js/calls_coaching_dashboard.js",
            "doorway_vicidial_campaigns/static/src/xml/calls_coaching_dashboard.xml",
            "doorway_vicidial_campaigns/static/src/js/my_coaching_dashboard.js",
            "doorway_vicidial_campaigns/static/src/xml/my_coaching_dashboard.xml",
            "doorway_vicidial_campaigns/static/src/css/my_coaching_dashboard.css",
            "doorway_vicidial_campaigns/static/src/js/supervisor_dashboard.js",
            "doorway_vicidial_campaigns/static/src/xml/supervisor_dashboard.xml",
            "doorway_vicidial_campaigns/static/src/css/supervisor_dashboard.css",
            "doorway_vicidial_campaigns/static/src/js/vicidial_qualification_hub.js",
            "doorway_vicidial_campaigns/static/src/xml/vicidial_qualification_hub.xml",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
