# -*- coding: utf-8 -*-
{
    "name": "Coins Québec",
    "version": "19.0.1.37.1",
    "category": "Services",
    "summary": "Plateforme Coins Québec : biens, réservations, partenaires, chauffeurs, parrainage (CAD)",
    "description": """
Coins Québec — module métier indépendant (clone structurel de Coins Marocain).

Tables dédiées coins.quebec.* : aucune donnée partagée avec coins_marocain.
Devise CAD. Taxes TPS/TVQ via la société Agence Doorway.
Catégories biens : Découverte, Privatisation, Événements, Bien-être, Hébergement.
""",
    "author": "IntelliX / Agence Doorway",
    "depends": [
        "base",
        "mail",
        "contacts",
        "crm",
        "sales_team",
        "calendar",
        "web",
        "doorway_agents_dashboard",
        "portal",
        "sale",
    ],
    "data": [
        "security/coins_security.xml",
        "security/ir.model.access.csv",
        "security/rdv_security.xml",
        "data/sequences.xml",
        "data/categories.xml",
        "data/carnet_tiers.xml",
        "data/crm_pipeline.xml",
        "data/pipeline_cleanup.xml",
        "data/mail_template_data.xml",
        "data/mail_template_intro_entente.xml",
        "data/mon_coin_activity.xml",
        "data/mon_coin_demo.xml",
        "data/mon_coin_products.xml",
        "views/property_views.xml",
        "views/reservation_views.xml",
        "views/partner_views.xml",
        "views/evenement_views.xml",
        "views/prestataire_views.xml",
        "views/driver_views.xml",
        "views/forfait_views.xml",
        "views/carnet_views.xml",
        "views/ota_views.xml",
        "views/dashboard_views.xml",
        "views/pipeline_views.xml",
        "views/partenariat_bonus_views.xml",
        "views/book_rdv_wizard_views.xml",
        "views/rdv_views.xml",
        "views/rdv_dashboard_views.xml",
        "wizard/rdv_reject_wizard_views.xml",
        "wizard/planifier_evenement_wizard_views.xml",
        "wizard/send_entente_wizard_views.xml",
        "views/mon_coin_backend.xml",
        "views/mon_coin_product_views.xml",
        "views/menus.xml",
        "templates/mon_coin_layout.xml",
        "templates/mon_coin_pages.xml",
        "templates/carte_publique.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "coins_quebec/static/src/css/quebec_theme.css",
            "coins_quebec/static/src/js/quebec_theme.js",
        ],
        "web.assets_web_dark": [
            "coins_quebec/static/src/css/quebec_theme.css",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
    "sequence": 2,
    "license": "LGPL-3",
}
