# -*- coding: utf-8 -*-
{
    "name": "RH",
    "version": "19.0.6.0.44",
    "category": "Human Resources",
    "summary": "RH Doorway — coaching IA, LMS, primes, présence, paie, juridique",
    "description": "Module RH Doorway : performance, coaching, formation, primes, présence VICIdial, paie temps réel, dashboard TV, juridique n8n.",
    "author": "Agence Doorway Inc.",
    "depends": [
        "hr",
        "hr_holidays",
        "hr_timesheet",
        "crm",
        "project",
        "mail",
        "base",
        "account",
        "analytic",
        "website",
        "renovation_conciergerie",
        "gamification",
        "doorway_onboarding",
        "doorway_agents_dashboard",
        "doorway_vicidial_campaigns",
        "doorway_traffic_manager",
        "doorway_leads_bruts",
        "lead_automation_hub",
    ],
    "external_dependencies": {
        "python": ["mysql-connector-python"],
        'controllers': ['controllers/'],
},
    "data": [
        "security/pe_security.xml",
        "security/ir.model.access.csv",
        "data/pe_doorway_access.xml",
        "data/pe_superadmin_access.xml",
        "data/pe_menu_fix.xml",
        "data/pe_score_weights.xml",
        "data/pe_metrics_config.xml",
        "data/pe_action_types.xml",
        "data/pe_ai_prompt.xml",
        "data/pe_sequences.xml",
        "data/pe_lifecycle_stages_data.xml",
        "data/pe_document_templates_data.xml",
        "data/pe_document_templates_catalog.xml",
        "data/legal_quebec_data.xml",
        "data/legal_france_data.xml",
        "data/legal_morocco_data.xml",
        "data/badges_data.xml",
        "data/levels_data.xml",
        "data/courses_data.xml",
        "data/course_agent_ia_qualification_update.xml",
        "data/course_crm_intellix_update.xml",
        "data/course_rh_gamification_update.xml",
        "data/course_renovation_immobilier_update.xml",
        "data/pe_quiz_demo_data.xml",
        "data/learning_paths_data.xml",
        "data/prime_rules_data.xml",
        "data/pe_prime_templates_data.xml",
        "data/tv_config_data.xml",
        "data/pe_cron.xml",
        "data/pe_phase4_config.xml",
        "data/pe_payroll_config.xml",
        "data/pe_payroll_sequences.xml",
        "data/pe_disciplinary_sequences.xml",
        "data/pe_disciplinary_config.xml",
        "data/pe_payroll_cron.xml",
        "data/pe_payroll_challenge_cron.xml",
        "data/pe_disciplinary_cron.xml",
        "data/pe_absence_sequences.xml",
        "data/pe_absence_cron.xml",
        "data/pe_kpi_cron.xml",
        "data/pe_celebration_config.xml",
        "data/pe_celebration_templates_data.xml",
        "data/pe_celebration_cron.xml",
        "data/pe_objective_templates_data.xml",
        "data/pe_department_template.xml",
        "data/callcenter_template_data.xml",
        "data/callcenter_maroc_data.xml",
        "data/callcenter_badges_data.xml",
        "data/callcenter_challenges_data.xml",
        "data/callcenter_crons.xml",
        "views/pe_employee_profile_views.xml",
        "views/pe_employee_profile_mockup_views.xml",
        "views/pe_employee_profile_team_views.xml",
        "views/hr_employee_views.xml",
        "views/pe_objective_views.xml",
        "views/pe_objective_template_views.xml",
        "views/pe_evaluation_views.xml",
        "views/pe_performance_score_views.xml",
        "views/pe_action_log_views.xml",
        "views/coaching_views.xml",
        "views/coaching_session_views.xml",
        "views/development_plan_views.xml",
        "views/team_dashboard_views.xml",
        "views/legal_views.xml",
        "views/pe_document_views.xml",
        "reports/pe_employee_letter_report.xml",
        "views/gamification_views.xml",
        "views/lms_views.xml",
        "views/prime_views.xml",
        "views/pe_prime_template_views.xml",
        "views/tv_dashboard.xml",
        "views/pe_leaderboard_views.xml",
        "views/pe_call_log_views.xml",
        "views/pe_cc_campaign_views.xml",
        "views/pe_callcenter_agent_view.xml",
        "views/pe_callcenter_supervisor_view.xml",
        "views/pe_callcenter_wall_view.xml",
        "views/dashboard_employee.xml",
        "views/dashboard_manager.xml",
        "views/dashboard_hr.xml",
        "wizards/score_refresh_wizard.xml",
        "wizards/evaluation_wizard.xml",
        "wizards/coaching_wizard.xml",
        "wizards/reward_wizard.xml",
        "wizards/invite_collaborator.xml",
        "wizards/pe_profile_onboarding_wizard.xml",
        "views/pe_access_views.xml",
        "data/pe_onboarding_badge.xml",
        "data/onboarding_bridge.xml",
        "templates/tv_display.xml",
        "templates/lms_portal.xml",
        "views/pe_phase4_views.xml",
        "views/menus.xml",
        "views/pe_quiz_views.xml",
        "views/hr_admin_menus.xml",
        "views/hr_menu_hide.xml",
        "views/pe_payroll_views.xml",
        "views/pe_payroll_challenge_views.xml",
        "wizards/pe_freelance_invoice_wizard.xml",
        "views/pe_freelance_invoice_views.xml",
        "views/pe_disciplinary_views.xml",
        "views/pe_absence_views.xml",
        "views/pe_kpi_snapshot_views.xml",
        "wizards/pe_celebration_manual_wizard.xml",
        "wizards/pe_apply_objective_template_wizard.xml",
        "wizards/pe_save_objective_template_wizard.xml",
        "views/pe_celebration_views.xml",
        "wizards/pe_disciplinary_wizard.xml",
        "reports/pe_payroll_bulletin_report.xml",
        "reports/pe_freelance_invoice_report.xml",
        "reports/pe_disciplinary_letter_report.xml",
        "views/crm_lead_coaching_views.xml",
        "views/pe_rh_hub.xml",
        "data/intellix_app_menu_order.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "people_engine/static/src/js/pe_rh_theme_patch.js",
            "people_engine/static/src/xml/pe_rh_hub.xml",
            "people_engine/static/src/js/pe_rh_hub.js",
            "people_engine/static/src/css/pe_course_viewer.css",
            "people_engine/static/src/xml/pe_course_viewer.xml",
            "people_engine/static/src/js/pe_course_viewer.js",
            "people_engine/static/src/components/quiz_player/quiz_player.xml",
            "people_engine/static/src/components/quiz_player/quiz_player.js",
            "people_engine/static/src/components/quiz_player/quiz_player.scss",
            "people_engine/static/src/scss/pe_rh_hub.scss",
            "people_engine/static/src/css/people_engine.css",
            "people_engine/static/src/css/pe_employee_form_mockup.css",
            "people_engine/static/src/css/pe_team_dashboard.css",
            "people_engine/static/src/css/people_engine_dashboard.css",
            "people_engine/static/src/js/team_dashboard_utils.js",
            "people_engine/static/src/js/team_dashboard.js",
            "people_engine/static/src/js/pe_team_list_controller.js",
            "people_engine/static/src/xml/pe_team_list.xml",
            "people_engine/static/src/xml/team_dashboard.xml",
            "people_engine/static/src/js/coaching_list.js",
            "people_engine/static/src/xml/coaching_list.xml",
            "people_engine/static/src/js/dev_plan_list.js",
            "people_engine/static/src/xml/dev_plan_list.xml",
            "people_engine/static/src/js/progress_bar_field.js",
            "people_engine/static/src/pe_onboarding/pe_onboarding.scss",
            "people_engine/static/src/js/pe_callcenter_wall.js",
            "people_engine/static/src/xml/pe_callcenter_wall.xml",
            "people_engine/static/src/js/pe_supervisor_pause_dashboard.js",
            "people_engine/static/src/js/people_engine_open_pe.js",
            "people_engine/static/src/pe_onboarding/pe_onboarding_confetti.js",
            "people_engine/static/src/pe_onboarding/pe_onboarding_form_controller.js",
            "people_engine/static/src/xml/pe_supervisor_pause_dashboard.xml",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
    "post_init_hook": "post_init_hook",
    "license": "LGPL-3",
}
