# -*- coding: utf-8 -*-
{
    "name": "Agents IA",
    "version": "19.0.3.80",
    "category": "CRM",
    "summary": "Dashboard agents, coaching, sync n8n/ElevenLabs, VICIdial",
    "depends": [
        "base",
        "mail",
        "web",
        "crm",
        "sales_team",
        "base_setup",
        "intellix_branding",
        "doorway_onboarding",
        "calendar",
    ],
    "external_dependencies": {
        "python": [
            "twilio",
            "anthropic",
            "requests",
            "mysql-connector-python",
            "PyJWT",
        ],
    },
    "data": [
        "security/agents_dashboard_security.xml",
        "security/ir.model.access.csv",
        "data/cron_data.xml",
        "data/agents_ia_cron_data.xml",
        "data/onboarding.xml",
        "data/agent_action_tags_data.xml",
        "data/agents_data.xml",
        "data/maison_recherchee_agent.xml",
        "data/maison_recherchee_qualification.xml",
        "data/maison_recherchee_library.xml",
        "data/maison_recherchee_relance_agents.xml",
        "data/maison_immo_sync.xml",
        "data/energie_pro_agent.xml",
        "data/energie_pro_relance_agents.xml",
        "data/energie_pro_sync.xml",
        "data/haidly_agent.xml",
        "data/haidly_relance_agents.xml",
        "data/haidly_sync.xml",
        "data/sofia_renov_agent.xml",
        "data/sofia_es_production.xml",
        "data/soumission_qc_agent.xml",
        "data/renofacile_fr_agent.xml",
        "data/sip_trunk_espagne.xml",
        "data/zakaria_booking_config.xml",
        "data/intellix_crm_tags.xml",
        "data/lea_qc_scripted_lines.xml",
        "data/driven_b2b_agent.xml",
        "data/driven_b2b_cron.xml",
        "data/lea_fr_scripted_lines.xml",
        "views/res_config_settings_views.xml",
        "views/agent_wizard_views.xml",
        "views/agent_performance_views.xml",
        "views/agent_performance_search.xml",
        "views/agent_performance_form_tab.xml",
        "views/agent_performance_kanban.xml",
        "views/agents_dashboard.xml",
        "views/agent_profile_views.xml",
        "views/test_call_views.xml",
        "views/dashboard_live.xml",
        "views/report_views.xml",
        "views/agent_ia_views.xml",
        "views/lea_qc_metrics_views.xml",
        "views/agent_menu.xml",
        "views/calendar_views.xml",
        "views/res_users_calendar_views.xml",
        "wizard/call_coaching_wizard_views.xml",
        "wizard/doorway_videoconf_wizard_views.xml",
        "views/videoconf_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "doorway_agents_dashboard/static/src/xml/agents_dashboard.xml",
            "doorway_agents_dashboard/static/src/xml/agent_wizard.xml",
            "doorway_agents_dashboard/static/src/xml/performance_dashboard.xml",
            "doorway_agents_dashboard/static/src/xml/ia_agents_live_dashboard.xml",
            "doorway_agents_dashboard/static/src/xml/agent_chart_widget.xml",
            "doorway_agents_dashboard/static/src/xml/agent_web_call.xml",
            "doorway_agents_dashboard/static/src/js/rpc_error.js",
            "doorway_agents_dashboard/static/src/js/agents_dashboard.js",
            "doorway_agents_dashboard/static/src/js/agent_wizard.js",
            "doorway_agents_dashboard/static/src/js/performance_dashboard.js",
            "doorway_agents_dashboard/static/src/js/ia_agents_live_dashboard.js",
            "doorway_agents_dashboard/static/src/js/agent_chart_widget.js",
            "doorway_agents_dashboard/static/src/js/agent_web_call.js",
            "doorway_agents_dashboard/static/src/css/agents.css",
            "doorway_agents_dashboard/static/src/css/intellix_agents.css",
            "doorway_agents_dashboard/static/src/css/agent_web_call.css",
            "doorway_agents_dashboard/static/src/css/agents_theme_fix.css",
            "doorway_agents_dashboard/static/src/css/agent_dashboard.css",
            "doorway_agents_dashboard/static/src/css/ia_agents_live_dashboard.css",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
    "pre_init_hook": "pre_init_hook",
    "post_init_hook": "post_init_hook",
}
