# -*- coding: utf-8 -*-
{
    "name": "Coins Marocain — Partenariats & Influenceurs",
    "version": "19.0.1.45.0",
    "category": "Services",
    "summary": "Suivi influenceurs et ententes partenaires (Coins Marocain)",
    "description": """
Suivi des influenceurs et gestion des ententes / partenariats
pour Coins Marocain (restaurants, riads, wedding planners,
agences de voyage, organisateurs de congrès).

Module séparé : ne modifie pas chauffeurs, réservations ni packages.
Envoi du lien d'activation via doorway_messaging.

Dashboard partenaires ITEX (maquette dark) : portail /my/coins-partenaires
+ action backend OWL — stats live, sans nouveau modèle métier.
""",
    "author": "IntelliX / Agence Doorway",
    "depends": [
        "coins_marocain",
        "doorway_messaging",
        "mail",
        "contacts",
        "crm",
        "sale",
        "sale_management",
        "sale_crm",
        "intellix_catalog",
        "portal",
        "website",
        "people_engine",
        "doorway_agents_dashboard",
    ],
    "data": [
        "security/groups.xml",
        "security/partner_rules.xml",
        "security/ir.model.access.csv",
        "data/crm_pipeline_coins_marocain.xml",
        "data/crm_pipeline_voyageurs.xml",
        "data/crm_pipeline_voyageurs_relance.xml",
        "data/crm_pipeline_partnership_align.xml",
        "data/mail_template_data.xml",
        "views/crm_lead_intro_bonjour_views.xml",
        "views/crm_lead_signature_views.xml",
        "data/mail_template_signature_karine.xml",
        "data/mail_activity_voyageur.xml",
        "data/mail_template_voyageur.xml",
        "data/voyageur_sheet_sync.xml",
        "data/coins_partner_products.xml",
        "data/coins_partner_quotation_templates.xml",
        "data/coins_quebec_partner_products.xml",
        "data/coins_quebec_quotation_templates.xml",
        "wizard/coins_entente_activation_wizard_views.xml",
        "wizard/coins_devis_entente_wizard_views.xml",
        "wizard/book_rdv_wizard_views.xml",
        "wizard/planifier_evenement_wizard_views.xml",
        "wizard/send_fiche_wizard_views.xml",
        "views/sale_order_template_views.xml",
        "views/coins_influenceur_views.xml",
        "views/account_invoice_report.xml",
        "views/coins_entente_views.xml",
        "views/coins_entente_activation_views.xml",
        "views/coins_partenariat_kpi_views.xml",
        "views/coins_partenariats_menus.xml",
        "views/crm_lead_search_views.xml",
        "views/crm_lead_partenariat_views.xml",
        "views/crm_lead_scrape_views.xml",
        "views/crm_lead_voyageur_views.xml",
        "views/coins_lead_classification_views.xml",
        "views/crm_pipeline_menus.xml",
        "views/partenaires_dashboard_views.xml",
        "templates/partenaires_dashboard.xml",
        "data/kpi_targets.xml",
        "data/devis_workspace_setup.xml",
        "data/fix_quebec_clauses.xml",
    ],
    "post_init_hook": "post_init_hook",
    "assets": {
        "web.assets_backend": [
            "coins_marocain_partenariats/static/src/css/coins_pipeline_kanban.css",
            "coins_marocain_partenariats/static/src/js/coins_pipeline_theme.js",
            "coins_marocain_partenariats/static/src/css/partenaires_dashboard.css",
            "coins_marocain_partenariats/static/src/js/partenaires_dashboard.js",
            "coins_marocain_partenariats/static/src/js/invalid_fields_toast.js",
            "coins_marocain_partenariats/static/src/xml/partenaires_dashboard.xml",
            "coins_marocain_partenariats/static/src/css/equipe_kpi_dashboard.css",
            "coins_marocain_partenariats/static/src/js/equipe_kpi_dashboard.js",
            "coins_marocain_partenariats/static/src/xml/equipe_kpi_dashboard.xml",
        ],
        "web.assets_web_dark": [
            "coins_marocain_partenariats/static/src/css/coins_pipeline_kanban.css",
            "coins_marocain_partenariats/static/src/css/partenaires_dashboard.css",
            "coins_marocain_partenariats/static/src/css/equipe_kpi_dashboard.css",
        ],
        "web.assets_frontend": [
            "coins_marocain_partenariats/static/src/css/partenaires_dashboard.css",
        ],
    },
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
